version: '3'

services:
  postgresdev:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgdev
  flyway-migrations:
    image: jimmyoak/flyway:4.0.3
    command: wait-for-it --timeout=30 --strict postgresdev:5432 -- flyway migrate
    volumes:
      - '../flyway-migrations/conf:/flyway/conf'
      - '../flyway-migrations/sql:/flyway/sql'
    depends_on:
      - postgresdev
